apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nodeapp
  namespace: ingress-tls
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: __AKS_IMAGE__
          ports:
          - containerPort: 80
